language: node_js
node_js:
- "8"
sudo: true
dist: trusty

branches:
  only:
  - master

script:
- ng build --prod

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_AUTH_TOKEN
    app: tour-of-heroes
